ALTER TABLE `products` ADD `stock` FLOAT NULL DEFAULT NULL AFTER `price`;
ALTER TABLE `reviews` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, add PRIMARY KEY (`id`);

ALTER TABLE `customers` ADD `phone` VARCHAR(100) NULL DEFAULT NULL AFTER `image`;